# -*- coding: utf-8 -*-
"""Tinyimagenet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PlRevesP88GvZ0cR3PwVss22NCXZFc2f
"""

from google.colab import drive
drive.mount('/content/drive')

#!wget http://cs231n.stanford.edu/tiny-imagenet-200.zip

#!unzip "/content/tiny-imagenet-200.zip" -d "/content/drive/MyDrive/TinyImage"

#Test data 
import os
testdata = os.listdir('/content/drive/MyDrive/TinyImage/tiny-imagenet-200/test/images') # dir is your directory path
test_files = len(testdata)
print (test_files)

# Count of Validation images
valdata = os.listdir('/content/drive/MyDrive/TinyImage/tiny-imagenet-200/val/images') # dir is your directory path
val_files = len(valdata)
print (val_files)

/content/drive/MyDrive/TinyImage/tiny-imagenet-200/val/train

traindata = os.listdir('/content/drive/MyDrive/TinyImage/tiny-imagenet-200/val/train') # dir is your directory path
train_files = len(traindata)
print (train_files)

#print (traindata)

#Count of train images
path ="/content/drive/MyDrive/TinyImage/tiny-imagenet-200/train"
train_count = 0
for root, dirs, files in os.walk(path):
  #print(os.walk(path))
  #print(files)
  for file in files:
    if(file.endswith(".JPEG")):
      train_count += 1
      
      #print(len(os.path.join(root,file)))

#Count of Validation images
path ='/content/drive/MyDrive/TinyImage/tiny-imagenet-200/val/images"
val_count = 0
for root, dirs, files in os.walk(path):
  #print(os.walk(path))
  #print(files)
  for file in files:
    if(file.endswith(".JPEG")):
      val_count += 1

"""The dataset used for my experiments is the Tiny
ImageNet dataset. It contains a training set of 100,000
images, a validation set of 10,000 images, and a test
set of also 10,000 images. These images are sourced
from 200 different classes of objects. The images are
downscaled from the orig
"""

print('Count of train images'+ train_count)
print('count of test images' + test_files)
print('count of validation images'+ )